#!/bin/bash
ram_usage_percentage=$(free | awk '/Mem/ {printf "%.2f", ($3/$2)*100}')

ram_total=$(free -h | awk '/Mem/ {print $2}')

icon="📊"

printf "%.2f%% %s (%s)\\n" "$ram_usage_percentage" "$icon" "$ram_total"

